package com.demo.entities;
// Generated Nov 8, 2024, 3:46:28 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * DeliveryInfo generated by hbm2java
 */
@Entity
@Table(name = "delivery_info", catalog = "music_store")
public class DeliveryInfo implements java.io.Serializable {

	private Integer id;
	private User user;
	private String phone;
	private String province;
	private String district;
	private String ward;
	private String addressDetails;
	private Boolean status;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public DeliveryInfo() {
	}

	public DeliveryInfo(User user, String phone, String province, String district, String ward, String addressDetails,
			Boolean status, Set<Payment> payments) {
		this.user = user;
		this.phone = phone;
		this.province = province;
		this.district = district;
		this.ward = ward;
		this.addressDetails = addressDetails;
		this.status = status;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "province", length = 50)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "district", length = 50)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "ward", length = 50)
	public String getWard() {
		return this.ward;
	}

	public void setWard(String ward) {
		this.ward = ward;
	}

	@Column(name = "address_details")
	public String getAddressDetails() {
		return this.addressDetails;
	}

	public void setAddressDetails(String addressDetails) {
		this.addressDetails = addressDetails;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryInfo")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	@Override
	public String toString() {
		return "DeliveryInfo [id=" + id + ", user=" + user + ", phone=" + phone + ", province=" + province
				+ ", district=" + district + ", ward=" + ward + ", addressDetails=" + addressDetails + ", status="
				+ status + ", payments=" + payments + "]";
	}

}
