package com.demo.entities;
// Generated Nov 8, 2024, 3:46:28 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", catalog = "music_store")
public class Genre implements java.io.Serializable {

	private Integer id;
	private String name;
	private Boolean status;
	private Set<Cd> cds = new HashSet<Cd>(0);

	public Genre() {
	}

	public Genre(String name, Boolean status, Set<Cd> cds) {
		this.name = name;
		this.status = status;
		this.cds = cds;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Cd> getCds() {
		return this.cds;
	}

	public void setCds(Set<Cd> cds) {
		this.cds = cds;
	}

}
