package com.demo.entities;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "music_store")
public class Order implements java.io.Serializable {

	private Integer id;
	private User user;
	private Date orderDate;
	private BigDecimal totalAmount;
	private Integer status;
	private String reason; // Thêm trường lý do hủy
	private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Order() {
	}

	public Order(User user, Date orderDate, BigDecimal totalAmount, Integer status, String reason,
			Set<Orderdetails> orderdetailses, Set<Payment> payments) {
		this.user = user;
		this.orderDate = orderDate;
		this.totalAmount = totalAmount;
		this.status = status;
		this.reason = reason; // Khởi tạo trường reason
		this.orderdetailses = orderdetailses;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", length = 10)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "total_amount", precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "reason", length = 255) // Ánh xạ với cột 'reason' trong cơ sở dữ liệu
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Orderdetails> getOrderdetailses() {
		return this.orderdetailses;
	}

	public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
		this.orderdetailses = orderdetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}
}
