package com.demo.entities;
// Generated Nov 8, 2024, 3:46:28 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "music_store")
public class Payment implements java.io.Serializable {

	private Integer id;
	private DeliveryInfo deliveryInfo;
	private Order order;
	private String transactionNo;
	private Date created;
	private String description;
	private BigDecimal price;
	private Boolean status;

	public Payment() {
	}

	public Payment(DeliveryInfo deliveryInfo, Order order, String transactionNo, Date created, String description,
			BigDecimal price, Boolean status) {
		this.deliveryInfo = deliveryInfo;
		this.order = order;
		this.transactionNo = transactionNo;
		this.created = created;
		this.description = description;
		this.price = price;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "delivery_info_id")
	public DeliveryInfo getDeliveryInfo() {
		return this.deliveryInfo;
	}

	public void setDeliveryInfo(DeliveryInfo deliveryInfo) {
		this.deliveryInfo = deliveryInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "transaction_no", length = 50)
	public String getTransactionNo() {
		return this.transactionNo;
	}

	public void setTransactionNo(String transactionNo) {
		this.transactionNo = transactionNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "Payment [id=" + id + ", deliveryInfo=" + deliveryInfo + ", order=" + order + ", transactionNo="
				+ transactionNo + ", created=" + created + ", description=" + description + ", price=" + price
				+ ", status=" + status + "]";
	}

}
